### PR TITLE
Add option to build with CUDAToolkit and enable_language(CUDA)

### PR DESCRIPTION
**Pull request by peterbell10**
`find_package(CUDA)` is deprecated in newer versions of cmake. This adds the `GLOO_USE_CUDA_TOOLKIT` option to build with `enable_language(CUDA)` and `find_package(CUDAToolkit)` which are the modern cmake replacements. 

cc @malfet

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Sounds good to me, but I wonder how do you plan to test it

**Comment by peterbell10** [comment]
I have https://github.com/pytorch/pytorch/pull/83199 setup to build with my fork of gloo and with `GLOO_USE_CUDA_TOOLKIT` set.

**Comment by peterbell10** [comment]
I notice there's no build with CUDA 11 here. Maybe A new CI job for CUDA 11 with `GLOO_USE_CUDA_TOOLKIT` defined would be useful?

**Comment by peterbell10** [comment]
@malfet I've got the CI job running. The build log shows:
```
-- Found CUDAToolkit: /usr/local/cuda/include (found suitable version "11.7.99", minimum required is "7.0") 
```
and also files show `Building CUDA object`, whereas when using `cuda_add_library` they show up as `Building NVCC (Device) object`.

**Comment by malfet** [comment]
Got internal approval, landing...

**Pull request closed without merging**
