### PR TITLE
Updates to Hip.cmake to support recent ROCm

### PR DESCRIPTION
**Pull request by pruthvistony**
- Remove deprecated HIP_PATH
- Cleanup of unused variables

### CODE REVIEW

**Comment by fduwjj** [comment]
Looks like CI failed?

**Review by malfet — APPROVED** [review]

**Comment by pruthvistony** [comment]
@fduwjj 
Changes are only ROCm related.

**Comment by malfet** [comment]
@fduwjj CI has been broken for a year or so. Changes proposed here are noop for existing CI

**Comment by fduwjj** [comment]
@malfet if so, shall we remove that test from CI?

**Comment by malfet** [comment]
@fduwjj it would be better to fix it, let's see if https://github.com/facebookincubator/gloo/pull/373 will work

**Pull request closed without merging**
