### PR TITLE
[PTD][Oncall] bump version of gloo after fix

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #349

See https://github.com/facebookincubator/gloo/pull/346.

Differential Revision: [D42582672](https://our.internmc.facebook.com/intern/diff/D42582672)

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
LGTM!

**Review by kumpera — APPROVED** [review]
LGTM

**Comment by fduwjj** [comment]
Not needed

**Pull request closed without merging**
