### PR TITLE
[contbuild] Travis contbuild scripts and cmake fix.

### PR DESCRIPTION
**Pull request by Yangqing**
TSIA

@JoelMarcey - could you turn on travis for gloo? I do not have ownership of the facebookincubator org.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@Yangqing I believe I have enabled it for gloo; can you verify?

**Comment by JoelMarcey** [comment]
I think you will need a `.travis.yml` file added and then push a commit to trigger it.

**Comment by JoelMarcey** [comment]
You may have to close/re-open this pull request to trigger it for this specific one.

**Comment by Yangqing** [comment]
Lovely, thanks @JoelMarcey - I saw travis being turned on indeed. Will do a dummy PR refresh to trigger it.

**Pull request closed without merging**
