### PR TITLE
Add amd/rocm support for gloo

### PR DESCRIPTION
**Pull request by petrex**
The goal of this PR is to add automation to generate HIP kernels for AMD platform and request feedback/comment for future direction. 

Currently, the PR built with Rocm release 1.9.2 and there is a parallel effort in [pytorch/caffe2](https://github.com/pytorch/pytorch/pull/12130). A collection of docker images can be found [here](https://hub.docker.com/r/bddppq/pytorch-rocm/).

To build this PR ,

- In a ROCM compatible environment, run the hipify script 
`python ./amd_build/hipify_gloo.py` 

- Build the project with `USE_HIP=ON`

RCCL support would be in separate PRs. Feedback and comments are very welcome!

### CODE REVIEW

**Comment by pietern** [comment]
Thanks for your work @petrex!

I tried compiling with -DUSE_HIP=ON and get an error that `gloo/hip_private.h` is not found. Looks like it is referred in `hip.cc` but not present in the tree.

**Comment by pietern** [comment]
Nevermind, had to run `amd_build/hipify_gloo.py`.

**Comment by pietern** [comment]
Thanks for updating @petrex. I'm running into an issue when building with `-DBUILD_TEST=ON` now. It looks like the include path to HIP headers does not propagate to the test binary. Looking into making a quick fix for this myself in getting this to compile..

**Comment by pietern** [comment]
See https://gist.github.com/pietern/199660a927ef746cf74cd72dab22c74e for the patch I did on top of this PR. It now generates a HIP version of `cuda_base_test.cu` in `gloo/test` as well, but it can't find the `<hip/hip_runtime.h>` header. Looks like the include path is not set for `hip_add_executable`:

```
/usr/bin/c++  -DNDEBUG -I../ -I. -I/opt/rocm/hcc/include -I/home/pietern/usr/include -std=c++11 -fPIC -O3 -DNDEBUG -MD -MT gloo/test/CMakeFiles/gloo_test_hip.dir/hip_allreduce_builder_test.cc.o -MF gloo/test/CMakeFiles/gloo_test_hip.dir/hip_allreduce_builder_test.cc.o.d -o gloo/test/CMakeFiles/gloo_test_hip.dir/hip_allreduce_builder_test.cc.o -c ../gloo/test/hip_allreduce_builder_test.cc
FAILED: gloo/test/CMakeFiles/gloo_test_hip.dir/hip_allreduce_builder_test.cc.o
/usr/bin/c++  -DNDEBUG -I../ -I. -I/opt/rocm/hcc/include -I/home/pietern/usr/include -std=c++11 -fPIC -O3 -DNDEBUG -MD -MT gloo/test/CMakeFiles/gloo_test_hip.dir/hip_allreduce_builder_test.cc.o -MF gloo/test/CMakeFiles/gloo_test_hip.dir/hip_allreduce_builder_test.cc.o.d -o gloo/test/CMakeFiles/gloo_test_hip.dir/hip_allreduce_builder_test.cc.o -c ../gloo/test/hip_allreduce_builder_test.cc
In file included from ../gloo/hip_private.h:19:0,
                 from ../gloo/test/hip_base_test.h:12,
                 from ../gloo/test/hip_allreduce_builder_test.cc:10:
../gloo/hip.h:16:10: fatal error: hip/hip_runtime.h: No such file or directory
 #include <hip/hip_runtime.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by petrex** [comment]
I am closing this PR. pls, refer to #173 for the latest integration on rocm 2.2

**Pull request closed without merging**
